# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Z-Leila
email: zxlLeila@gmail.com
description: >
  A web fullstack developer
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://Z-Leila.github.io" # the base hostname & protocol for your site
github_username: Z-Leila

# Build settings
markdown: kramdown
